[workspace]
members = [
    "crates/fe-core",
    "crates/fe-macros",
    "crates/fe-signals",
    "crates/fe-runtime",
    "crates/fe-components",
    "crates/fe-styles",
    "examples/hello-world"
]

