[package]
name = "fe-hello-world"
version = "0.1.0"
edition = "2021"


[dependencies]
fe-core = { path = "../../crates/fe-core" }
fe-styles = { path = "../../crates/fe-styles" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["console"] }

[lib]
crate-type = ["cdylib", "rlib"]
