[package]
name = "fe-core"
version = "0.1.0"
edition = "2021"

[dependencies]
fe-macros = { path = "../fe-macros/" }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Document", "Element", "Node"] }
fe-signals = { path = "../fe-signals" }

